//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.27 at 07:09:02 PM IST 
//


package com.test;

import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.test package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ExtendedSettingsDeleteSettings_QNAME = new QName("", "DeleteSettings");
    private final static QName _ExtendedSettingsUpdateSettings_QNAME = new QName("", "UpdateSettings");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.test
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ExtendedSettings }
     * 
     */
    public ExtendedSettings createExtendedSettings() {
        return new ExtendedSettings();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link List }{@code <}{@link String }{@code >}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DeleteSettings", scope = ExtendedSettings.class)
    public JAXBElement<List<String>> createExtendedSettingsDeleteSettings(List<String> value) {
        return new JAXBElement<List<String>>(_ExtendedSettingsDeleteSettings_QNAME, ((Class) List.class), ExtendedSettings.class, ((List<String> ) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link List }{@code <}{@link String }{@code >}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UpdateSettings", scope = ExtendedSettings.class)
    public JAXBElement<List<String>> createExtendedSettingsUpdateSettings(List<String> value) {
        return new JAXBElement<List<String>>(_ExtendedSettingsUpdateSettings_QNAME, ((Class) List.class), ExtendedSettings.class, ((List<String> ) value));
    }

}
